version: '3.8'
services:
  api:
    build:
      dockerfile: Dockerfile
      context: .
    depends_on:
      - db
      - cache
    environment:
      - NODE_ENV
      - PORT
      - DATABASE_TYPE
      - DATABASE_HOST
      - DATABASE_PORT
      - DATABASE_USERNAME
      - DATABASE_PASSWORD
      - DATABASE
      - ACCESS_TOKEN_SECRET
      - REFRESH_TOKEN_SECRET
      - EMAIL_HOST
      - EMAIL_PORT
      - EMAIL_USER
      - EMAIL_PASSWORD
      - REDIS_URL
    ports:
      - "3000:3000"
    
  db:
    image: mysql:latest
    ports:
      - "3307:3306"
    environment:
      - DATABASE_PASSWORD
      - DATABASE
      - DATABASE_USERNAME
    volumes:
      - mysql-data:/var/lib/mysql
  
  cache:
    image: redis
    ports:
      - "6380:6379"

volumes:
  mysql-data: